config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VoteableArthur

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post

  validates :body, presence: true, length: { maximum: 260 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :login_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.new(comment_params) # TODO : app crash when comment body empty
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      @post.reload
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @comment)

    respond_to do |format|
      if @vote.valid?
        flash[:notice] = 'Your vote was counted'
        format.html { redirect_to :back }
        format.js
      else
        flash[:error] = 'You can only vote on a comment once.'
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/views/comments/_comment.html.erb
<div class="row comment-block" data-votes=<%= comment.total_votes %> data-voteable-id=<%=comment.id %>>
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: :post, remote: true do %>
        <%= content_tag(:i, '', class: 'icon-arrow-up') %>
      <% end %>
      <br/>
    <% end %>
    <div id=<%= "comment-#{comment.id}-votes" %>>
      <%= comment.total_votes %> votes
    </div>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: :post, remote: true do %>
        <%= content_tag(:i, '', class: 'icon-arrow-down') %>
      <% end %>
    <% end %>
  </div>
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post_name %>
     on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br>
    <span class="quiet">by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    <small><%= custom_time_ago_in_words(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  var comment_votes = $('<%= "#comment-#{@comment.id}-votes" %>');
  comment_votes.html('<%= @comment.total_votes %> votes');
  comment_votes.closest('.comment-block').attr('data-votes', <%= @comment.total_votes %>);

  var comments_block = $('#comments-block');
  var comments = comments_block.find('.comment-block');

  comments.sort(function(a,b){
    var av = a.getAttribute('data-votes'),
        bv = b.getAttribute('data-votes');

    if(av > bv) {
      return -1;
    }
    if(av < bv) {
      return 1;
    }

    var aid = a.getAttribute('data-voteable-id'),
        bid = b.getAttribute('data-voteable-id');

    if(aid > bid) {
      return -1;
    }
    if(aid < bid) {
      return 1;
    }

    return 0;
  });

  comments.detach().appendTo(comments_block);
<% end %>