config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VoteableArthur
  include SluggableArthur

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 5, maximum: 120 }
  validates :url, presence: true, length: { maximum: 120 }, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :login_user, except: [:index, :show]
  before_action :creator_user_or_admin, only: [:edit, :update]

  def index
    @posts = sort_voteable(Post.all)

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = "Post Created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post Updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)

    respond_to do |format|
      if @vote.valid?
        flash[:notice] = 'Your vote was counted'
        format.html { redirect_to :back }
        format.js
      else
        flash[:error] = 'You can only vote on a post once.'
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private

    def set_post
      @post = Post.find_by(slug: params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
    end

    def creator_user_or_admin
      unless current_user?(@post.creator) || current_user.admin?
        flash[:error] = "You can't do that."
        redirect_to root_path
      end
    end

end

app/views/posts/_form.html.erb
<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label 'title' %>
      <%= f.text_field 'title' %>
    </div>
    <div class='control-group'>
      <%= f.label 'url' %>
      <%= f.text_field 'url' %>
    </div>
    <div class='control-group'>
      <%= f.label 'description' %>
      <%= f.text_area 'description', rows: 5 %>
    </div>
    <div class="control-group">
      <%= f.label 'category_ids', 'Categories' %>
      <%= f.collection_check_boxes 'category_ids', all_categories, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
      <% end %>
    </div>
    <%= f.submit @post.new_record? ? 'Create Post' : 'Update', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row post-block" data-votes=<%= post.total_votes %> data-voteable-id=<%=post.id %>>
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: :post, remote: true do %>
        <%= content_tag(:i, '', class: 'icon-arrow-up') %>
      <% end %>
      <br/>
    <% end %>
    <div id=<%= "post-#{post.id}-votes" %>>
      <%= post.total_votes %> votes
    </div>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: false), method: :post, remote: true do %>
        <%= content_tag(:i, '', class: 'icon-arrow-down') %>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url), target: '_blank' %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posed by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small><%= custom_time_ago_in_words(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post) )%>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Editing Post' %>
<%= render 'shared/errors', obj: @post %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<div id="posts-block">
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'shared/errors', obj: @post %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? && (current_user?(@post.creator) || current_user.admin? ) %>
  <p class="pull-right">
    <%= link_to '[edit this post]', edit_post_path(@post) %>
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr>

<%= render 'shared/errors', obj: @comment %>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <div class="control-group" >
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, class: 'span4', rows: 3 %>
    </div>
    <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h5>Comments:</h5>

<div id="comments-block" >
  <%= render partial: 'comments/comment', collection: sort_voteable(@post.comments), locals: {show_post_name: false} %>
</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  var post_votes = $('<%= "#post-#{@post.id}-votes" %>');
  post_votes.html('<%= @post.total_votes %> votes');
  post_votes.closest('.post-block').attr('data-votes', <%= @post.total_votes %>);

  console.log(post_votes.closest('.post-block'));

  var post_block = $('#posts-block');
  var posts = post_block.find('.post-block');

  posts.sort(function(a,b){
    var av = a.getAttribute('data-votes'),
        bv = b.getAttribute('data-votes');

    if(av > bv) {
      return -1;
    }
    if(av < bv) {
      return 1;
    }

    var aid = a.getAttribute('data-voteable-id'),
        bid = b.getAttribute('data-voteable-id');

    if(aid > bid) {
      return -1;
    }
    if(aid < bid) {
      return 1;
    }

    return 0;
  });

  posts.detach().appendTo(post_block);
<% end %>