config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include SluggableArthur

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }

  sluggable_column :name

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :login_user, except: [:show]
  before_action :admin_role, except: [:show]

  def show
    @category = Category.find_by(slug: params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "'#{@category.name}' category created."
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<div class="well">
  <%= form_for @category do |f| %>
    <div class='control-group' >
      <%= f.label 'name', 'Category Name' %>
      <%= f.text_field 'name' %>
    </div>
    <%= f.submit 'Create Category', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>
<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% breadcrumbs = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: breadcrumbs %>

<%= render @category.posts %>