config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class="btn-group nav_item">
  <%= link_to '#', class: "btn btn-small dropdown-toggle", 'data-toggle' => "dropdown" do %>
    Categories <span class="caret"></span>
  <% end %>>
  <ul class="dropdown-menu">
    <% all_categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <% end %>

    <% if admin? %>
      <li class="divider"></li>
      <li>
        <%= link_to(new_category_path) do %>
          <%= content_tag(:i, '', class: 'icon-plus') %> New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class="nav_item">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>

  <div class="btn-group nav_item">
    <%= link_to '#', class: "btn btn-small dropdown-toggle", 'data-toggle' => "dropdown" do %>
      <%= current_user.username%> <span class="caret"></span>
    <% end %>>
    <ul class="dropdown-menu">
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <%= content_tag(:i, '', class: 'icon-pencil') %> Edit Profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
          <%= content_tag(:i, '', class: 'icon-user') %> View Profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
          <%= content_tag(:i, '', class: 'icon-circle-arrow-left') %> Logout
        <% end %>
      </li>
    </ul>
  </div>
<% else %>
  <div class="nav_item">
    <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
  </div>

  <div class="nav_item">
    <%= link_to 'Login', login_path, class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <div id="flash-message">
              <%= render 'layouts/messages' %>
            </div>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application.js.erb
// FLASH NOTICE ANIMATION
var fade_flash = function() {
  var flash_message = $("#flash-message");

  if ( flash_message.is(':animated') )
    flash_message.stop(true,true).animate({opacity:1});

  flash_message.delay(5000).fadeOut("slow");
};

var show_ajax_message = function(msg, type) {
  var flash_message = $("#flash-message");

  //delete the flash message (if it was there before) when an ajax request returns no flash message
  if ( (type.indexOf("empty") == 0) || msg == null || (msg.length == 0) ) {
    flash_message.html("").hide();
    return;
  }

  var alert_type = (type.indexOf("error") == -1) ? 'alert-success' : 'alert-error';

  flash_message.html(
    "<div class='alert " + alert_type + "'><a class='close' data-dismiss='alert'>&#215;</a>" +
    "<div id='flash_" + type + "'>" + msg + "</div></div>"
  ).show();

  fade_flash();
};

$(document).ajaxComplete(function(event, request) {
  var msg = request.getResponseHeader('X-Message');
  var type = request.getResponseHeader('X-Message-Type');

  if (type.indexOf("keep") != 0)
    show_ajax_message(msg, type); //use whatever popup, notification or whatever plugin you want
});

<%= yield %>